name: Reload Repository CDN

on:
  push:
    branches:
      - main

jobs:
  reload-cdn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Reload CDN
        run: wget https://purge.jsdelivr.net/gh/yuzhanglong/serendipity@main

      - name: Show result
        run: cat ./serendipity@main
