name: Sync CNPM

on:
  push:
    branches:
      - main

jobs:
  sync-cnpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Chmod Scripts Files
        run: chmod 777 -R ./scripts

      - name: Sync CNPM
        run: ./scripts/cnpm-sync.sh